### ISSUE TITLE
Does not support aliases for status

### ISSUE THREAD

**Issue by drmacdon** [nguyenvukhang/gitnu#2]
I would like to use 'gitnu s' instead of 'gitnu status'.

I have a git alias s=status which works for git, but gitnu appears to ignore that alias.

**Comment by nguyenvukhang** [comment]
closed by https://github.com/nguyenvukhang/gitnu/commit/76855901b52b2b097405a36318918e6c7552d9f4 ([v0.7.0](https://github.com/nguyenvukhang/gitnu/releases/tag/v0.7.0))
